# This is a basic workflow to help you get started with Actions

name: Auto Build

on:
  schedule:
    - cron:  '0 3 * * *' # UTC

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_HUB_PASS }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

    - name: Update Images
      run: ./bin/01-update-images ${{ secrets.GITHUB_TOKEN }}

    - name: Update Readme
      run: ./bin/02-update-readme

    - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
      with:
        # The name of the user that will be displayed as the author of the commit
        # Default: author of the commit that triggered the run
        author_name: "bskrtich-ci"

        # The email of the user that will be displayed as the author of the commit
        # Default: author of the commit that triggered the run
        author_email: bskrtich-ci@bearded.io

        # Whether to use the --force option on `git add`, in order to bypass eventual gitignores
        # Default: false
        #force: true

        # The message for the commit
        # Default: 'Commit from GitHub Actions'
        message: 'CI: Autobuild Repo ${{ date -Iseconds }}'

      env:
        # This is necessary in order to push a commit to the repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged

    - name: Build Images
      run: ./bin/03-build-images push

    - name: Build Images
      run: ./bin/04-push-readme ${{ secrets.DOCKER_HUB_USER }} ${{ secrets.DOCKER_HUB_PASS }}
